apiVersion: batch/v1
kind: CronJob
metadata:
  name: k8s-cleanup
  namespace: kube-system
spec:
  schedule: "0 */3 * * *"
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      template:
        metadata:
          name: k8s-cleanup
        spec:
          nodeSelector:
            node-role.kubernetes.io/control-plane: ""
          tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/control-plane
          restartPolicy: OnFailure
          serviceAccountName: admin-user-kube-system
          containers:
            - name: k8s-cleanup
              image: ghcr.io/jc01rho/k8s-cleanup:latest
              command: ["/bin/bash", "/bin/k8s-clean.sh"]
              imagePullPolicy: Always
              resources:
                requests:
                  cpu: 100m
                  memory: 50Mi
