apiVersion: batch/v1
kind: CronJob
metadata:
  name: k8s-nerdctl-cleanup
  namespace: kube-system
spec:
  schedule: "0 23 */3 * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: k8s-nerdctl-cleanup
        spec:
          volumes:
            - name: containerdsocket
              hostPath:
                path: /run/containerd/containerd.sock
          containers:
          - name: k8s-nerdctl-cleanup
            image: ghcr.io/jc01rho/k8s-cleanup:latest
            imagePullPolicy: Always
            args:
              - "/bin/nerdctl-clean.sh"
            env:
              - name: CONATINERD_CLEAN_INTERVAL
                value: "259200"
                #3 days
            resources:
              requests:
                cpu: 100m
                memory: 50Mi
            volumeMounts:
              - name: containerdsocket
                mountPath: /run/containerd/containerd.sock
          restartPolicy: OnFailure