apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: k8s-nodes-vm-cache-clean
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: k8s-nodes-vm-cache-clean
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
  template:
    metadata:
      labels:
        app: k8s-nodes-vm-cache-clean
    spec:
      containers:
      - name: k8s-nodes-vm-cache-clean
        image: ghcr.io/jc01rho/k8s-cleanup:latest
        imagePullPolicy: Always
        args:
          - "/bin/vm-cache-clean.sh"
        securityContext:
          privileged: true
        env:
          - name: DROP_CACHES_INTERVAL
            value: "604800"
            #one week
        resources:
          requests:
            cpu: 100m
            memory: 50Mi

